export const CLEARED_COMPLETED = 'TODOS_CLEARED_COMPLETED';
export const COMPLETED_ALL = 'TODOS_COMPLETED_ALL';
export const CREATED_TODO = 'TODOS_CREATED_TODO';
export const DELETED_TODO = 'TODOS_DELETED_TODO';
export const UNCOMPLETED_ALL = 'TODOS_UNCOMPLETED_ALL';
export const UPDATED_TODO = 'TODOS_UPDATED_TODO';
